// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageWebAppClark.Models;

namespace MultiPageWebAppClark.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20220608180440_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultiPageWebAppClark.Models.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactID = 1,
                            ContactAddress = "Whitestone Castle, Whitestone",
                            ContactName = "Grog Strongjaw",
                            ContactNote = "also ale",
                            ContactPhone = "555-253-4764"
                        },
                        new
                        {
                            ContactID = 2,
                            ContactAddress = "Jedi Temple, Galactic City",
                            ContactName = "Obi-Wan Kenobi",
                            ContactNote = "Jedi Master",
                            ContactPhone = "555-367-2311"
                        },
                        new
                        {
                            ContactID = 3,
                            ContactAddress = "221B Baker Street, London",
                            ContactName = "Sherlock Holmes",
                            ContactNote = "Detective",
                            ContactPhone = "555-221-2583"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
